List<String> assetsSvgBackground = <String>[
  'assets/svg/background/1.svg',
  'assets/svg/background/2.svg',
  'assets/svg/background/3.svg',
  'assets/svg/background/4.svg',
  'assets/svg/background/5.svg',
  'assets/svg/background/6.svg',
  'assets/svg/background/7.svg',
  'assets/svg/background/8.svg',
  'assets/svg/background/9.svg',
  'assets/svg/background/10.svg',
  'assets/svg/background/11.svg',
  'assets/svg/background/12.svg',
  'assets/svg/background/13.svg',
  'assets/svg/background/14.svg',
  'assets/svg/background/15.svg',
  'assets/svg/background/16.svg',
];